project:
  type: book
  output-dir: docs

book: 
  title: "Qualifying Exam Preparation"
  author: "Christian Testa"
  description: "Exercises and notes in preparation for PhD Qualifying Exams in Biostatistics"
  chapters:
    - index.qmd
    - part: 1_theory.qmd
      chapters:
      - 1_probability/01_background_puzzles.qmd
    - part: 2_inference.qmd
      chapters:
      - 2_inference/05_asymptotic_distributions.qmd
    - part: 3_methods.qmd
      chapters:
      - 3_methods/01_linear_regression.qmd
    - part: 4_datastructures.qmd
      chapters:
      - 4_datastructures/01_random_numbers.qmd
      - 4_datastructures/02_concepts.qmd
      - 4_datastructures/03_data_structures.qmd
      - 4_datastructures/04_heaps.qmd
      - 4_datastructures/05_greedy_and_dynamic_algorithms.qmd
      # - 3_datastructures/06_parallel_computing.qmd
      # - 3_datastructures/07_p_and_np.qmd
      # - 3_datastructures/08_numerical_aspects_of_algorithms.qmd
      # - 3_datastructures/09_linear_equations.qmd
      # - 3_datastructures/10_least_squares.qmd
      # - 3_datastructures/11_eigenvalues_and_sparse_matrices.qmd
      # - 3_datastructures/12_nonlinear_equations.qmd
      # - 3_datastructures/14_optimization.qmd
    - part: 5_appendix.qmd
      chapters:
      - 5_appendix/01_calculus.qmd
  sidebar: 
    collapse-level: 1

number-sections: true
bibliography: references.bib  
reference-location: margin
citation-location: margin
comments:
  giscus:
    repo: ctesta01/QualPrep

format: 
  html: 
    theme: style.scss
    number-sections: false
    sidebar: true
    toc: false
    toc-depth: 0